---
- name: Check if user exists
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Check for user existence
      ansible.builtin.shell: "id vidhumal"
      register: user_check
      ignore_errors: yes
    - name: Report user existence
      ansible.builtin.debug:
        var: user_check.stdout

